### ISSUE TITLE
Upstream the transparent borders fix

### ISSUE THREAD

**Issue by averms** [szatanjl/dwm#1]
Specifically commit 1529909466206016f2101457bbf37c67195714c8.
It seems like an obvious bug fix that they would accept.

**Comment by szatanjl** [comment]
I am actually planning on upstreaming my work, I am working on st at the moment, and once I am finished with it I will "binge-upstream".

BTW.  How did you come across my fork?

**Comment by averms** [comment]
> BTW. How did you come across my fork?

From https://github.com/yshui/picom/issues/285#issuecomment-625421356

**Comment by szatanjl** [comment]
Added "Fix transparent borders" section on alpha patch site: <https://dwm.suckless.org/patches/alpha/>.
